name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21  # Replace with the correct port if it's different
        local-dir: ./  # This is the directory to deploy; adjust as needed
        server-dir: /potensikaryamandiri.com/  # Adjust if your site is in a subdirectory